# This file is generated by data-raw/write_parametra_outputs.R.
# Do not edit manually.

#' PARAMETRA transmission data
#'
#' Reproduction number, transmission parameter, probability of infection given direct/indirect contact, probability of reactivation of latent infection and other transmission parameters
#'
#' @format A data frame.
#' @details Columns:
#' \describe{\item{estimation_method}{Method used for estimation}}
#' \describe{\item{estimation_type}{Statistical approach used (Frequentist/Bayesian)}}
#' \describe{\item{filled_by}{Data entry person identifier}}
#' \describe{\item{filled_date}{Data entry date}}
#' \describe{\item{host}{Host species}}
#' \describe{\item{host_age}{Age or age group of host}}
#' \describe{\item{host_breed}{Specific breed of host}}
#' \describe{\item{host_other}{Additional host characteristics}}
#' \describe{\item{host_type}{Type of host}}
#' \describe{\item{id}{Parameter identifier}}
#' \describe{\item{if_other}{Additional parameter specifications}}
#' \describe{\item{lower_cl}{Lower bound of confidence/credible interval}}
#' \describe{\item{model_mixing}{Mixing pattern in the population}}
#' \describe{\item{model_scale}{Scale of the model}}
#' \describe{\item{model_type}{Model classification (e.g., SI, SIR)}}
#' \describe{\item{parameter}{Parameter measured}}
#' \describe{\item{pathogen}{Name of the infectious agent}}
#' \describe{\item{ref}{Reference: source DOI or URL}}
#' \describe{\item{ref_last_access}{Date reference was automatically checked for the last time}}
#' \describe{\item{ref_short}{Short reference: source author and year}}
#' \describe{\item{ref_status}{Reference status in the last aoutomatic check}}
#' \describe{\item{remarks}{Additional notes or comments}}
#' \describe{\item{study_type}{Study type}}
#' \describe{\item{unit}{Units of measurement}}
#' \describe{\item{upper_cl}{Upper bound of confidence/credible interval}}
#' \describe{\item{vaccine}{Type of vaccine used if applicable}}
#' \describe{\item{vaccine_contact}{Vaccination status of contact animals}}
#' \describe{\item{vaccine_seeder}{Vaccination status of seeder/inoculated animals}}
#' \describe{\item{value}{Numeric value of the parameter}}
#' \describe{\item{variant_strain}{Specific variant or strain}}
#' \describe{\item{year}{Year of publication}}
"transmission"

#' PARAMETRA infectious_latent_incuba_period data
#'
#' Infectious period, latent period, incubation period, shape and other disease period parameters
#'
#' @format A data frame.
#' @details Columns:
#' \describe{\item{estimation_method}{Method used for estimation}}
#' \describe{\item{estimation_type}{Statistical approach used (Frequentist/Bayesian)}}
#' \describe{\item{filled_by}{Data entry person identifier}}
#' \describe{\item{filled_date}{Data entry date}}
#' \describe{\item{host}{Host species}}
#' \describe{\item{host_age}{Age or age group of host}}
#' \describe{\item{host_breed}{Specific breed of host}}
#' \describe{\item{host_other}{Additional host characteristics}}
#' \describe{\item{host_type}{Type of host}}
#' \describe{\item{id}{Parameter identifier}}
#' \describe{\item{if_other}{Additional parameter specifications}}
#' \describe{\item{inoculated_contact}{Inoculation of contact status}}
#' \describe{\item{lower_cl}{Lower bound of confidence/credible interval}}
#' \describe{\item{parameter}{Parameter measured}}
#' \describe{\item{pathogen}{Name of the infectious agent}}
#' \describe{\item{ref}{Reference: source DOI or URL}}
#' \describe{\item{ref_last_access}{Date reference was automatically checked for the last time}}
#' \describe{\item{ref_short}{Short reference: source author and year}}
#' \describe{\item{ref_status}{Reference status in the last aoutomatic check}}
#' \describe{\item{remarks}{Additional notes or comments}}
#' \describe{\item{scale}{Scale of the study}}
#' \describe{\item{study_type}{Study type}}
#' \describe{\item{unit}{Units of measurement}}
#' \describe{\item{upper_cl}{Upper bound of confidence/credible interval}}
#' \describe{\item{vaccine}{Type of vaccine used if applicable}}
#' \describe{\item{value}{Numeric value of the parameter}}
#' \describe{\item{variant_strain}{Specific variant or strain}}
#' \describe{\item{year}{Year of publication}}
"infectious_latent_incuba_period"

#' PARAMETRA pathogen_survival data
#'
#' Survival parameters in different materials and environmental conditions
#'
#' @format A data frame.
#' @details Columns:
#' \describe{\item{filled_by}{Data entry person identifier}}
#' \describe{\item{filled_date}{Data entry date}}
#' \describe{\item{id}{Parameter identifier}}
#' \describe{\item{if_other}{Additional parameter specifications}}
#' \describe{\item{material}{Type of material or medium where survival was measured}}
#' \describe{\item{parameter}{Parameter measured}}
#' \describe{\item{pathogen}{Name of the infectious agent}}
#' \describe{\item{ref}{Reference: source DOI or URL}}
#' \describe{\item{ref_last_access}{Date reference was automatically checked for the last time}}
#' \describe{\item{ref_short}{Short reference: source author and year}}
#' \describe{\item{ref_status}{Reference status in the last aoutomatic check}}
#' \describe{\item{remarks}{Additional notes or comments}}
#' \describe{\item{study_type}{Study type}}
#' \describe{\item{variant_strain}{Specific variant or strain}}
#' \describe{\item{year}{Year of publication}}
"pathogen_survival"

#' PARAMETRA diagnostic_test data
#'
#' Diagnostic test parameters such as test specificity and sensitivity
#'
#' @format A data frame.
#' @details Columns:
#' \describe{\item{filled_by}{Data entry person identifier}}
#' \describe{\item{filled_date}{Data entry date}}
#' \describe{\item{host}{Host species}}
#' \describe{\item{host_age}{Age or age group of host}}
#' \describe{\item{host_breed}{Specific breed of host}}
#' \describe{\item{host_other}{Additional host characteristics}}
#' \describe{\item{host_type}{Type of host}}
#' \describe{\item{id}{Parameter identifier}}
#' \describe{\item{lower_cl}{Lower bound of confidence/credible interval}}
#' \describe{\item{parameter}{Parameter measured}}
#' \describe{\item{pathogen}{Name of the infectious agent}}
#' \describe{\item{ref}{Reference: source DOI or URL}}
#' \describe{\item{ref_last_access}{Date reference was automatically checked for the last time}}
#' \describe{\item{ref_short}{Short reference: source author and year}}
#' \describe{\item{ref_status}{Reference status in the last aoutomatic check}}
#' \describe{\item{remarks}{Additional notes or comments}}
#' \describe{\item{sample_type}{Type of biological sample used}}
#' \describe{\item{study_type}{Study type}}
#' \describe{\item{test_type}{Type of diagnostic test used}}
#' \describe{\item{upper_cl}{Upper bound of confidence/credible interval}}
#' \describe{\item{value}{Numeric value of the parameter}}
#' \describe{\item{year}{Year of publication}}
"diagnostic_test"

#' PARAMETRA within_herd_prevalence data
#'
#' Within-herd pathogen prevalence parameters
#'
#' @format A data frame.
#' @details Columns:
#' \describe{\item{filled_by}{Data entry person identifier}}
#' \describe{\item{filled_date}{Data entry date}}
#' \describe{\item{host}{Host species}}
#' \describe{\item{host_age}{Age or age group of host}}
#' \describe{\item{host_breed}{Specific breed of host}}
#' \describe{\item{host_other}{Additional host characteristics}}
#' \describe{\item{host_type}{Type of host}}
#' \describe{\item{id}{Parameter identifier}}
#' \describe{\item{lower_cl}{Lower bound of confidence/credible interval}}
#' \describe{\item{parameter}{Parameter measured}}
#' \describe{\item{pathogen}{Name of the infectious agent}}
#' \describe{\item{ref}{Reference: source DOI or URL}}
#' \describe{\item{ref_last_access}{Date reference was automatically checked for the last time}}
#' \describe{\item{ref_short}{Short reference: source author and year}}
#' \describe{\item{ref_status}{Reference status in the last aoutomatic check}}
#' \describe{\item{remarks}{Additional notes or comments}}
#' \describe{\item{study_type}{Study type}}
#' \describe{\item{time_period}{Time period of the study}}
#' \describe{\item{upper_cl}{Upper bound of confidence/credible interval}}
#' \describe{\item{value}{Numeric value of the parameter}}
#' \describe{\item{year}{Year of publication}}
"within_herd_prevalence"

#' PARAMETRA regional_prevalence data
#'
#' Regional pathogen prevalence parameters at country or sub-division level
#'
#' @format A data frame.
#' @details Columns:
#' \describe{\item{country}{Country or region where data was collected}}
#' \describe{\item{filled_by}{Data entry person identifier}}
#' \describe{\item{host}{Host species}}
#' \describe{\item{host_age}{Age or age group of host}}
#' \describe{\item{host_breed}{Specific breed of host}}
#' \describe{\item{host_other}{Additional host characteristics}}
#' \describe{\item{host_type}{Type of host}}
#' \describe{\item{id}{Parameter identifier}}
#' \describe{\item{info_level}{Geographical level of information detail}}
#' \describe{\item{parameter}{Parameter measured}}
#' \describe{\item{pathogen}{Name of the infectious agent}}
#' \describe{\item{ref}{Reference: source DOI or URL}}
#' \describe{\item{ref_last_access}{Date reference was automatically checked for the last time}}
#' \describe{\item{ref_short}{Short reference: source author and year}}
#' \describe{\item{ref_status}{Reference status in the last aoutomatic check}}
#' \describe{\item{remarks}{Additional notes or comments}}
#' \describe{\item{sampling_purpose}{Purpose of the sampling conducted}}
#' \describe{\item{study_type}{Study type}}
#' \describe{\item{time_period}{Time period of the study}}
#' \describe{\item{year}{Year of publication}}
"regional_prevalence"

#' PARAMETRA control_plan data
#'
#' Information about disease control programs and plans implemented in different countries
#'
#' @format A data frame.
#' @details Columns:
#' \describe{\item{country}{Country or region where data was collected}}
#' \describe{\item{country_disease_status}{Disease status classification}}
#' \describe{\item{filled_by}{Data entry person identifier}}
#' \describe{\item{host}{Host species}}
#' \describe{\item{host_age}{Age or age group of host}}
#' \describe{\item{host_breed}{Specific breed of host}}
#' \describe{\item{host_other}{Additional host characteristics}}
#' \describe{\item{host_type}{Type of host}}
#' \describe{\item{id}{Parameter identifier}}
#' \describe{\item{last_updated}{Date of last control plan update}}
#' \describe{\item{pathogen}{Name of the infectious agent}}
#' \describe{\item{plan_coverage}{Geographical scope of the plan}}
#' \describe{\item{plan_implemented}{Whether a control plan is implemented}}
#' \describe{\item{plan_type}{Type of control plan}}
#' \describe{\item{plan_voluntary_compulsary}{Voluntary or compulsory plan}}
#' \describe{\item{ref}{Reference: source DOI or URL}}
#' \describe{\item{ref_last_access}{Date reference was automatically checked for the last time}}
#' \describe{\item{ref_short}{Short reference: source author and year}}
#' \describe{\item{ref_status}{Reference status in the last aoutomatic check}}
#' \describe{\item{remarks}{Additional notes or comments}}
#' \describe{\item{year}{Year of publication}}
"control_plan"

#' PARAMETRA cost_biosecurity data
#'
#' Information about prices of products needed to implement biosecurity measures
#'
#' @format A data frame.
#' @details Columns:
#' \describe{\item{biosecurity_measure}{Category of measure}}
#' \describe{\item{country}{Country or region where data was collected}}
#' \describe{\item{filled_by}{Data entry person identifier}}
#' \describe{\item{filled_date}{Data entry date}}
#' \describe{\item{id}{Parameter identifier}}
#' \describe{\item{last_access}{URL last access date}}
#' \describe{\item{lifespan}{Expected lifespan of the product if applicable and based on typical usage}}
#' \describe{\item{parameter}{Parameter measured}}
#' \describe{\item{price}{Price of the product available online without VAT}}
#' \describe{\item{price_by_event}{Total cost per event to implement the biosecurity measure without VAT}}
#' \describe{\item{product_name}{Commercial name of the product}}
#' \describe{\item{product_type}{Specific type of product needed to implement the biosecurity measure}}
#' \describe{\item{qty_by_event}{Quantity of the product used per event to implement the biosecurity measure}}
#' \describe{\item{ref}{Reference: source DOI or URL}}
#' \describe{\item{ref_last_access}{Date reference was automatically checked for the last time}}
#' \describe{\item{ref_short}{Short reference: source author and year}}
#' \describe{\item{ref_status}{Reference status in the last aoutomatic check}}
#' \describe{\item{remarks}{Additional notes or comments}}
#' \describe{\item{transmission_pathway}{Transmission pathway targeted by this biosecurity measure}}
#' \describe{\item{unit_needed}{Unit of the product needed per event to implement the biosecurity measure (e.g. gram, liter, unit)}}
#' \describe{\item{year_cost}{Year the cost was included}}
"cost_biosecurity"

#' PARAMETRA other data
#'
#' Additional parameters and information related to various infectious diseases in animal populations that do not fit into other specific categories
#'
#' @format A data frame.
#' @details Columns:
#' \describe{\item{estimation_type}{Statistical approach used (Frequentist/Bayesian)}}
#' \describe{\item{filled_by}{Data entry person identifier}}
#' \describe{\item{filled_date}{Data entry date}}
#' \describe{\item{host}{Host species}}
#' \describe{\item{host_age}{Age or age group of host}}
#' \describe{\item{host_breed}{Specific breed of host}}
#' \describe{\item{host_other}{Additional host characteristics}}
#' \describe{\item{host_type}{Type of host}}
#' \describe{\item{id}{Parameter identifier}}
#' \describe{\item{if_other}{Additional parameter specifications}}
#' \describe{\item{lower_cl}{Lower bound of confidence/credible interval}}
#' \describe{\item{model_type}{Model classification (e.g., SI, SIR)}}
#' \describe{\item{parameter}{Parameter measured}}
#' \describe{\item{pathogen}{Name of the infectious agent}}
#' \describe{\item{ref}{Reference: source DOI or URL}}
#' \describe{\item{ref_last_access}{Date reference was automatically checked for the last time}}
#' \describe{\item{ref_short}{Short reference: source author and year}}
#' \describe{\item{ref_status}{Reference status in the last aoutomatic check}}
#' \describe{\item{remarks}{Additional notes or comments}}
#' \describe{\item{study_type}{Study type}}
#' \describe{\item{unit}{Units of measurement}}
#' \describe{\item{upper_cl}{Upper bound of confidence/credible interval}}
#' \describe{\item{vaccine}{Type of vaccine used if applicable}}
#' \describe{\item{value}{Numeric value of the parameter}}
#' \describe{\item{variant_strain}{Specific variant or strain}}
#' \describe{\item{year}{Year of publication}}
"other"

#' PARAMETRA Crossref data
#'
#' Metadata extracted from CrossRef using the rcrossref package for scientific publications referenced in the parametra_long dataset
#'
#' @format A data frame.
#' @details Columns:
#' \describe{\item{id}{Parameter identifier}}
#' \describe{\item{ref}{Reference: source DOI or URL}}
#' \describe{\item{ref_last_access}{Date reference was automatically checked for the last time}}
#' \describe{\item{ref_status}{Reference status in the last aoutomatic check}}
"crossref"

#' PARAMETRA long-format data
#'
#' Curated PARAMETRA records from all parameter sheets combined in long format.
#'
#' @format A data frame.
#' @details Columns:
#' \describe{\item{biosecurity_measure}{Category of measure}}
#' \describe{\item{country}{Country or region where data was collected}}
#' \describe{\item{country_disease_status}{Disease status classification}}
#' \describe{\item{estimation_method}{Method used for estimation}}
#' \describe{\item{estimation_type}{Statistical approach used (Frequentist/Bayesian)}}
#' \describe{\item{filled_by}{Data entry person identifier}}
#' \describe{\item{filled_date}{Data entry date}}
#' \describe{\item{host}{Host species}}
#' \describe{\item{host_age}{Age or age group of host}}
#' \describe{\item{host_breed}{Specific breed of host}}
#' \describe{\item{host_other}{Additional host characteristics}}
#' \describe{\item{host_type}{Type of host}}
#' \describe{\item{id}{Parameter identifier}}
#' \describe{\item{if_other}{Additional parameter specifications}}
#' \describe{\item{info_level}{Geographical level of information detail}}
#' \describe{\item{inoculated_contact}{Inoculation of contact status}}
#' \describe{\item{last_access}{URL last access date}}
#' \describe{\item{last_updated}{Date of last control plan update}}
#' \describe{\item{lifespan}{Expected lifespan of the product if applicable and based on typical usage}}
#' \describe{\item{lower_cl}{Lower bound of confidence/credible interval}}
#' \describe{\item{material}{Type of material or medium where survival was measured}}
#' \describe{\item{model_mixing}{Mixing pattern in the population}}
#' \describe{\item{model_scale}{Scale of the model}}
#' \describe{\item{model_type}{Model classification (e.g., SI, SIR)}}
#' \describe{\item{parameter}{Parameter measured}}
#' \describe{\item{pathogen}{Name of the infectious agent}}
#' \describe{\item{plan_coverage}{Geographical scope of the plan}}
#' \describe{\item{plan_implemented}{Whether a control plan is implemented}}
#' \describe{\item{plan_type}{Type of control plan}}
#' \describe{\item{plan_voluntary_compulsary}{Voluntary or compulsory plan}}
#' \describe{\item{price}{Price of the product available online without VAT}}
#' \describe{\item{price_by_event}{Total cost per event to implement the biosecurity measure without VAT}}
#' \describe{\item{product_name}{Commercial name of the product}}
#' \describe{\item{product_type}{Specific type of product needed to implement the biosecurity measure}}
#' \describe{\item{qty_by_event}{Quantity of the product used per event to implement the biosecurity measure}}
#' \describe{\item{ref}{Reference: source DOI or URL}}
#' \describe{\item{ref_last_access}{Date reference was automatically checked for the last time}}
#' \describe{\item{ref_short}{Short reference: source author and year}}
#' \describe{\item{ref_status}{Reference status in the last aoutomatic check}}
#' \describe{\item{remarks}{Additional notes or comments}}
#' \describe{\item{sample_type}{Type of biological sample used}}
#' \describe{\item{sampling_purpose}{Purpose of the sampling conducted}}
#' \describe{\item{scale}{Scale of the study}}
#' \describe{\item{study_type}{Study type}}
#' \describe{\item{test_type}{Type of diagnostic test used}}
#' \describe{\item{time_period}{Time period of the study}}
#' \describe{\item{transmission_pathway}{Transmission pathway targeted by this biosecurity measure}}
#' \describe{\item{unit}{Units of measurement}}
#' \describe{\item{unit_needed}{Unit of the product needed per event to implement the biosecurity measure (e.g. gram, liter, unit)}}
#' \describe{\item{upper_cl}{Upper bound of confidence/credible interval}}
#' \describe{\item{vaccine}{Type of vaccine used if applicable}}
#' \describe{\item{vaccine_contact}{Vaccination status of contact animals}}
#' \describe{\item{vaccine_seeder}{Vaccination status of seeder/inoculated animals}}
#' \describe{\item{value}{Numeric value of the parameter}}
#' \describe{\item{variant_strain}{Specific variant or strain}}
#' \describe{\item{year}{Year of publication}}
#' \describe{\item{year_cost}{Year the cost was included}}
"parametra_long"

#' PARAMETRA Crossref metadata
#'
#' Crossref metadata for DOI references used in PARAMETRA.
#'
#' @format A data frame.
"parametra_crossref"

