# This file is generated by data-raw/write_parametra_outputs.R.
# Do not edit manually.

#' PARAMETRA transmission data
#'
#' Reproduction number, transmission parameter, probability of infection given direct/indirect contact, probability of reactivation of latent infection and other transmission parameters
#'
#' @format A data frame.
#'
#' @details
#' Columns:
#' \describe{
#'   \item{estimation_method}{Method used for estimation}
#'   \item{estimation_type}{Statistical approach used (Frequentist/Bayesian)}
#'   \item{filled_by}{Data entry person identifier}
#'   \item{filled_date}{Data entry date}
#'   \item{host}{Host species}
#'   \item{host_age}{Age or age group of host}
#'   \item{host_breed}{Specific breed of host}
#'   \item{host_other}{Additional host characteristics}
#'   \item{host_type}{Type of host}
#'   \item{id}{Parameter identifier}
#'   \item{if_other}{Additional parameter specifications}
#'   \item{lower_cl}{Lower bound of confidence/credible interval}
#'   \item{model_mixing}{Mixing pattern in the population}
#'   \item{model_scale}{Scale of the model}
#'   \item{model_type}{Model classification (e.g., SI, SIR)}
#'   \item{parameter}{Parameter measured}
#'   \item{pathogen}{Name of the infectious agent}
#'   \item{ref}{Reference: source DOI or URL}
#'   \item{ref_last_access}{Date reference was automatically checked for the last time}
#'   \item{ref_short}{Short reference: source author and year}
#'   \item{ref_status}{Reference status in the last aoutomatic check}
#'   \item{remarks}{Additional notes or comments}
#'   \item{study_type}{Study type}
#'   \item{unit}{Units of measurement}
#'   \item{upper_cl}{Upper bound of confidence/credible interval}
#'   \item{vaccine}{Type of vaccine used if applicable}
#'   \item{vaccine_contact}{Vaccination status of contact animals}
#'   \item{vaccine_seeder}{Vaccination status of seeder/inoculated animals}
#'   \item{value}{Numeric value of the parameter}
#'   \item{variant_strain}{Specific variant or strain}
#'   \item{year}{Year of publication}
#' }
#'
#' @source Compiled from various scientific publications; see the "ref" column.
"transmission"

#' PARAMETRA infectious_latent_incuba_period data
#'
#' Infectious period, latent period, incubation period, shape and other disease period parameters
#'
#' @format A data frame.
#'
#' @details
#' Columns:
#' \describe{
#'   \item{estimation_method}{Method used for estimation}
#'   \item{estimation_type}{Statistical approach used (Frequentist/Bayesian)}
#'   \item{filled_by}{Data entry person identifier}
#'   \item{filled_date}{Data entry date}
#'   \item{host}{Host species}
#'   \item{host_age}{Age or age group of host}
#'   \item{host_breed}{Specific breed of host}
#'   \item{host_other}{Additional host characteristics}
#'   \item{host_type}{Type of host}
#'   \item{id}{Parameter identifier}
#'   \item{if_other}{Additional parameter specifications}
#'   \item{inoculated_contact}{Inoculation of contact status}
#'   \item{lower_cl}{Lower bound of confidence/credible interval}
#'   \item{parameter}{Parameter measured}
#'   \item{pathogen}{Name of the infectious agent}
#'   \item{ref}{Reference: source DOI or URL}
#'   \item{ref_last_access}{Date reference was automatically checked for the last time}
#'   \item{ref_short}{Short reference: source author and year}
#'   \item{ref_status}{Reference status in the last aoutomatic check}
#'   \item{remarks}{Additional notes or comments}
#'   \item{scale}{Scale of the study}
#'   \item{study_type}{Study type}
#'   \item{unit}{Units of measurement}
#'   \item{upper_cl}{Upper bound of confidence/credible interval}
#'   \item{vaccine}{Type of vaccine used if applicable}
#'   \item{value}{Numeric value of the parameter}
#'   \item{variant_strain}{Specific variant or strain}
#'   \item{year}{Year of publication}
#' }
#'
#' @source Compiled from various scientific publications; see the "ref" column.
"infectious_latent_incuba_period"

#' PARAMETRA pathogen_survival data
#'
#' Survival parameters in different materials and environmental conditions
#'
#' @format A data frame.
#'
#' @details
#' Columns:
#' \describe{
#'   \item{filled_by}{Data entry person identifier}
#'   \item{filled_date}{Data entry date}
#'   \item{id}{Parameter identifier}
#'   \item{if_other}{Additional parameter specifications}
#'   \item{material}{Type of material or medium where survival was measured}
#'   \item{parameter}{Parameter measured}
#'   \item{pathogen}{Name of the infectious agent}
#'   \item{ref}{Reference: source DOI or URL}
#'   \item{ref_last_access}{Date reference was automatically checked for the last time}
#'   \item{ref_short}{Short reference: source author and year}
#'   \item{ref_status}{Reference status in the last aoutomatic check}
#'   \item{remarks}{Additional notes or comments}
#'   \item{study_type}{Study type}
#'   \item{variant_strain}{Specific variant or strain}
#'   \item{year}{Year of publication}
#' }
#'
#' @source Compiled from various scientific publications; see the "ref" column.
"pathogen_survival"

#' PARAMETRA diagnostic_test data
#'
#' Diagnostic test parameters such as test specificity and sensitivity
#'
#' @format A data frame.
#'
#' @details
#' Columns:
#' \describe{
#'   \item{filled_by}{Data entry person identifier}
#'   \item{filled_date}{Data entry date}
#'   \item{host}{Host species}
#'   \item{host_age}{Age or age group of host}
#'   \item{host_breed}{Specific breed of host}
#'   \item{host_other}{Additional host characteristics}
#'   \item{host_type}{Type of host}
#'   \item{id}{Parameter identifier}
#'   \item{lower_cl}{Lower bound of confidence/credible interval}
#'   \item{parameter}{Parameter measured}
#'   \item{pathogen}{Name of the infectious agent}
#'   \item{ref}{Reference: source DOI or URL}
#'   \item{ref_last_access}{Date reference was automatically checked for the last time}
#'   \item{ref_short}{Short reference: source author and year}
#'   \item{ref_status}{Reference status in the last aoutomatic check}
#'   \item{remarks}{Additional notes or comments}
#'   \item{sample_type}{Type of biological sample used}
#'   \item{study_type}{Study type}
#'   \item{test_type}{Type of diagnostic test used}
#'   \item{upper_cl}{Upper bound of confidence/credible interval}
#'   \item{value}{Numeric value of the parameter}
#'   \item{year}{Year of publication}
#' }
#'
#' @source Compiled from various scientific publications; see the "ref" column.
"diagnostic_test"

#' PARAMETRA within_herd_prevalence data
#'
#' Within-herd pathogen prevalence parameters
#'
#' @format A data frame.
#'
#' @details
#' Columns:
#' \describe{
#'   \item{filled_by}{Data entry person identifier}
#'   \item{filled_date}{Data entry date}
#'   \item{host}{Host species}
#'   \item{host_age}{Age or age group of host}
#'   \item{host_breed}{Specific breed of host}
#'   \item{host_other}{Additional host characteristics}
#'   \item{host_type}{Type of host}
#'   \item{id}{Parameter identifier}
#'   \item{lower_cl}{Lower bound of confidence/credible interval}
#'   \item{parameter}{Parameter measured}
#'   \item{pathogen}{Name of the infectious agent}
#'   \item{ref}{Reference: source DOI or URL}
#'   \item{ref_last_access}{Date reference was automatically checked for the last time}
#'   \item{ref_short}{Short reference: source author and year}
#'   \item{ref_status}{Reference status in the last aoutomatic check}
#'   \item{remarks}{Additional notes or comments}
#'   \item{study_type}{Study type}
#'   \item{time_period}{Time period of the study}
#'   \item{upper_cl}{Upper bound of confidence/credible interval}
#'   \item{value}{Numeric value of the parameter}
#'   \item{year}{Year of publication}
#' }
#'
#' @source Compiled from various scientific publications; see the "ref" column.
"within_herd_prevalence"

#' PARAMETRA regional_prevalence data
#'
#' Regional pathogen prevalence parameters at country or sub-division level
#'
#' @format A data frame.
#'
#' @details
#' Columns:
#' \describe{
#'   \item{country}{Country or region where data was collected}
#'   \item{filled_by}{Data entry person identifier}
#'   \item{host}{Host species}
#'   \item{host_age}{Age or age group of host}
#'   \item{host_breed}{Specific breed of host}
#'   \item{host_other}{Additional host characteristics}
#'   \item{host_type}{Type of host}
#'   \item{id}{Parameter identifier}
#'   \item{info_level}{Geographical level of information detail}
#'   \item{parameter}{Parameter measured}
#'   \item{pathogen}{Name of the infectious agent}
#'   \item{ref}{Reference: source DOI or URL}
#'   \item{ref_last_access}{Date reference was automatically checked for the last time}
#'   \item{ref_short}{Short reference: source author and year}
#'   \item{ref_status}{Reference status in the last aoutomatic check}
#'   \item{remarks}{Additional notes or comments}
#'   \item{sampling_purpose}{Purpose of the sampling conducted}
#'   \item{study_type}{Study type}
#'   \item{time_period}{Time period of the study}
#'   \item{year}{Year of publication}
#' }
#'
#' @source Compiled from various scientific publications; see the "ref" column.
"regional_prevalence"

#' PARAMETRA control_plan data
#'
#' Information about disease control programs and plans implemented in different countries
#'
#' @format A data frame.
#'
#' @details
#' Columns:
#' \describe{
#'   \item{country}{Country or region where data was collected}
#'   \item{country_disease_status}{Disease status classification}
#'   \item{filled_by}{Data entry person identifier}
#'   \item{host}{Host species}
#'   \item{host_age}{Age or age group of host}
#'   \item{host_breed}{Specific breed of host}
#'   \item{host_other}{Additional host characteristics}
#'   \item{host_type}{Type of host}
#'   \item{id}{Parameter identifier}
#'   \item{last_updated}{Date of last control plan update}
#'   \item{pathogen}{Name of the infectious agent}
#'   \item{plan_coverage}{Geographical scope of the plan}
#'   \item{plan_implemented}{Whether a control plan is implemented}
#'   \item{plan_type}{Type of control plan}
#'   \item{plan_voluntary_compulsary}{Voluntary or compulsory plan}
#'   \item{ref}{Reference: source DOI or URL}
#'   \item{ref_last_access}{Date reference was automatically checked for the last time}
#'   \item{ref_short}{Short reference: source author and year}
#'   \item{ref_status}{Reference status in the last aoutomatic check}
#'   \item{remarks}{Additional notes or comments}
#'   \item{year}{Year of publication}
#' }
#'
#' @source Compiled from various scientific publications; see the "ref" column.
"control_plan"

#' PARAMETRA cost_biosecurity data
#'
#' Information about prices of products needed to implement biosecurity measures
#'
#' @format A data frame.
#'
#' @details
#' Columns:
#' \describe{
#'   \item{biosecurity_measure}{Category of measure}
#'   \item{country}{Country or region where data was collected}
#'   \item{filled_by}{Data entry person identifier}
#'   \item{filled_date}{Data entry date}
#'   \item{id}{Parameter identifier}
#'   \item{last_access}{URL last access date}
#'   \item{lifespan}{Expected lifespan of the product if applicable and based on typical usage}
#'   \item{parameter}{Parameter measured}
#'   \item{price}{Price of the product available online without VAT}
#'   \item{price_by_event}{Total cost per event to implement the biosecurity measure without VAT}
#'   \item{product_name}{Commercial name of the product}
#'   \item{product_type}{Specific type of product needed to implement the biosecurity measure}
#'   \item{qty_by_event}{Quantity of the product used per event to implement the biosecurity measure}
#'   \item{ref}{Reference: source DOI or URL}
#'   \item{ref_last_access}{Date reference was automatically checked for the last time}
#'   \item{ref_short}{Short reference: source author and year}
#'   \item{ref_status}{Reference status in the last aoutomatic check}
#'   \item{remarks}{Additional notes or comments}
#'   \item{transmission_pathway}{Transmission pathway targeted by this biosecurity measure}
#'   \item{unit_needed}{Unit of the product needed per event to implement the biosecurity measure (e.g. gram, liter, unit)}
#'   \item{year_cost}{Year the cost was included}
#' }
#'
#' @source Compiled from various scientific publications; see the "ref" column.
"cost_biosecurity"

#' PARAMETRA other data
#'
#' Additional parameters and information related to various infectious diseases in animal populations that do not fit into other specific categories
#'
#' @format A data frame.
#'
#' @details
#' Columns:
#' \describe{
#'   \item{estimation_type}{Statistical approach used (Frequentist/Bayesian)}
#'   \item{filled_by}{Data entry person identifier}
#'   \item{filled_date}{Data entry date}
#'   \item{host}{Host species}
#'   \item{host_age}{Age or age group of host}
#'   \item{host_breed}{Specific breed of host}
#'   \item{host_other}{Additional host characteristics}
#'   \item{host_type}{Type of host}
#'   \item{id}{Parameter identifier}
#'   \item{if_other}{Additional parameter specifications}
#'   \item{lower_cl}{Lower bound of confidence/credible interval}
#'   \item{model_type}{Model classification (e.g., SI, SIR)}
#'   \item{parameter}{Parameter measured}
#'   \item{pathogen}{Name of the infectious agent}
#'   \item{ref}{Reference: source DOI or URL}
#'   \item{ref_last_access}{Date reference was automatically checked for the last time}
#'   \item{ref_short}{Short reference: source author and year}
#'   \item{ref_status}{Reference status in the last aoutomatic check}
#'   \item{remarks}{Additional notes or comments}
#'   \item{study_type}{Study type}
#'   \item{unit}{Units of measurement}
#'   \item{upper_cl}{Upper bound of confidence/credible interval}
#'   \item{vaccine}{Type of vaccine used if applicable}
#'   \item{value}{Numeric value of the parameter}
#'   \item{variant_strain}{Specific variant or strain}
#'   \item{year}{Year of publication}
#' }
#'
#' @source Compiled from various scientific publications; see the "ref" column.
"other"

#' PARAMETRA Crossref data
#'
#' Metadata extracted from CrossRef using the rcrossref package for scientific publications referenced in the parametra_long dataset
#'
#' @format A data frame.
#'
#' @details
#' Columns:
#' \describe{
#'   \item{id}{Parameter identifier}
#'   \item{ref}{Reference: source DOI or URL}
#'   \item{ref_last_access}{Date reference was automatically checked for the last time}
#'   \item{ref_status}{Reference status in the last aoutomatic check}
#' }
#'
#' @source Compiled from various scientific publications; see the "ref" column.
"crossref"

#' PARAMETRA long-format data
#'
#' Curated PARAMETRA records from all parameter sheets combined in long format.
#'
#' @format A data frame.
#'
#' @details
#' Columns:
#' \describe{
#'   \item{biosecurity_measure}{Category of measure}
#'   \item{country}{Country or region where data was collected}
#'   \item{country_disease_status}{Disease status classification}
#'   \item{estimation_method}{Method used for estimation}
#'   \item{estimation_type}{Statistical approach used (Frequentist/Bayesian)}
#'   \item{filled_by}{Data entry person identifier}
#'   \item{filled_date}{Data entry date}
#'   \item{host}{Host species}
#'   \item{host_age}{Age or age group of host}
#'   \item{host_breed}{Specific breed of host}
#'   \item{host_other}{Additional host characteristics}
#'   \item{host_type}{Type of host}
#'   \item{id}{Parameter identifier}
#'   \item{if_other}{Additional parameter specifications}
#'   \item{info_level}{Geographical level of information detail}
#'   \item{inoculated_contact}{Inoculation of contact status}
#'   \item{last_access}{URL last access date}
#'   \item{last_updated}{Date of last control plan update}
#'   \item{lifespan}{Expected lifespan of the product if applicable and based on typical usage}
#'   \item{lower_cl}{Lower bound of confidence/credible interval}
#'   \item{material}{Type of material or medium where survival was measured}
#'   \item{model_mixing}{Mixing pattern in the population}
#'   \item{model_scale}{Scale of the model}
#'   \item{model_type}{Model classification (e.g., SI, SIR)}
#'   \item{parameter}{Parameter measured}
#'   \item{pathogen}{Name of the infectious agent}
#'   \item{plan_coverage}{Geographical scope of the plan}
#'   \item{plan_implemented}{Whether a control plan is implemented}
#'   \item{plan_type}{Type of control plan}
#'   \item{plan_voluntary_compulsary}{Voluntary or compulsory plan}
#'   \item{price}{Price of the product available online without VAT}
#'   \item{price_by_event}{Total cost per event to implement the biosecurity measure without VAT}
#'   \item{product_name}{Commercial name of the product}
#'   \item{product_type}{Specific type of product needed to implement the biosecurity measure}
#'   \item{qty_by_event}{Quantity of the product used per event to implement the biosecurity measure}
#'   \item{ref}{Reference: source DOI or URL}
#'   \item{ref_last_access}{Date reference was automatically checked for the last time}
#'   \item{ref_short}{Short reference: source author and year}
#'   \item{ref_status}{Reference status in the last aoutomatic check}
#'   \item{remarks}{Additional notes or comments}
#'   \item{sample_type}{Type of biological sample used}
#'   \item{sampling_purpose}{Purpose of the sampling conducted}
#'   \item{scale}{Scale of the study}
#'   \item{study_type}{Study type}
#'   \item{test_type}{Type of diagnostic test used}
#'   \item{time_period}{Time period of the study}
#'   \item{transmission_pathway}{Transmission pathway targeted by this biosecurity measure}
#'   \item{unit}{Units of measurement}
#'   \item{unit_needed}{Unit of the product needed per event to implement the biosecurity measure (e.g. gram, liter, unit)}
#'   \item{upper_cl}{Upper bound of confidence/credible interval}
#'   \item{vaccine}{Type of vaccine used if applicable}
#'   \item{vaccine_contact}{Vaccination status of contact animals}
#'   \item{vaccine_seeder}{Vaccination status of seeder/inoculated animals}
#'   \item{value}{Numeric value of the parameter}
#'   \item{variant_strain}{Specific variant or strain}
#'   \item{year}{Year of publication}
#'   \item{year_cost}{Year the cost was included}
#' }
#'
#' @source Compiled from various scientific publications; see the "ref" column.
"parametra_long"

#' PARAMETRA Crossref metadata
#'
#' Crossref metadata for DOI references used in PARAMETRA.
#'
#' @format A data frame.
#'
#' @source Metadata retrieved from Crossref for DOI references used in PARAMETRA.
"parametra_crossref"

